basePath: /api/v1
definitions:
    AWSConfig:
        properties:
            configSecret:
                type: string
            region:
                type: string
        title: 'AWSConfig-based Signing Agent config: used when Base `store` `type` is `aws`.'
        type: object
    AutoApprove:
        properties:
            enabled:
                type: boolean
            retryIntervalMaxSec:
                format: int64
                type: integer
            retryIntervalSec:
                format: int64
                type: integer
        type: object
    Base:
        properties:
            pin:
                format: int64
                type: integer
            qredoAPI:
                type: string
        type: object
    ClientFeedResponse:
        properties:
            coreClientID:
                description: The ID of the agent
                example: 98cTMMSPrDdcDDVU8idhuJGK2U1P4vmQcsp8wnED8pPR
                type: string
            expireTime:
                description: The time that the transaction will expire, utc unix time
                example: 1676184187
                format: int64
                type: integer
            id:
                description: The ID of the transaction
                example: 2IXwq4klvWbnPf1YaAc1XD85jJX
                type: string
            status:
                description: The status of the transaction
                example: pending
                type: string
            timestamp:
                description: The time that the transaction was started, utc unix time
                example: 1670341423
                format: int64
                type: integer
            type:
                description: The type of the transaction
                example: ApproveWithdraw
                type: string
        type: object
    ClientFullRegisterResponse:
        properties:
            agentID:
                type: string
            feedURL:
                type: string
        type: object
    ClientRegisterRequest:
        properties:
            APIKey:
                description: The API key for the partner API
                example: eyJrZXkiOiJHM0Fo... (truncated)
                type: string
            base64PrivateKey:
                description: The Base64-encoded private key pem of which the public key has been registered in the Partner API
                example: LS0tLS1CRUdJTiBS... (truncated)
                type: string
            name:
                description: The name of the agent
                example: test-agent
                type: string
        type: object
    ConfigResponse:
        properties:
            autoApproval:
                $ref: '#/definitions/AutoApprove'
            base:
                $ref: '#/definitions/Base'
            http:
                $ref: '#/definitions/HttpSettings'
            loadBalancing:
                $ref: '#/definitions/LoadBalancing'
            logging:
                $ref: '#/definitions/Logging'
            store:
                $ref: '#/definitions/Store'
            websocket:
                $ref: '#/definitions/WebSocketConf'
        type: object
    GenericResponse:
        properties:
            Code:
                description: The result code of the request
                example: 200
                format: int64
                type: integer
            Msg:
                description: The result message of the request
                example: OK
                type: string
        type: object
    GetClientResponse:
        properties:
            agentID:
                type: string
            feedURL:
                type: string
        type: object
    HealthCheckStatusResponse:
        properties:
            websocket:
                $ref: '#/definitions/WebsocketStatus'
        type: object
    HttpSettings:
        properties:
            CORSAllowOrigins:
                items:
                    type: string
                type: array
            TLS:
                $ref: '#/definitions/TLSConfig'
            addr:
                type: string
            logAllRequests:
                type: boolean
        type: object
    LoadBalancing:
        properties:
            actionIDExpirationSec:
                format: int64
                type: integer
            enable:
                type: boolean
            onLockErrorTimeoutMs:
                format: int64
                type: integer
            redis:
                $ref: '#/definitions/RedisConfig'
        type: object
    Logging:
        properties:
            format:
                type: string
            level:
                type: string
        type: object
    OciConfig:
        properties:
            compartment:
                type: string
            configSecret:
                type: string
            secretEncryptionKey:
                type: string
            vault:
                type: string
        type: object
    RedisConfig:
        properties:
            db:
                format: int64
                type: integer
            host:
                type: string
            password:
                type: string
            port:
                format: int64
                type: integer
        type: object
    Store:
        properties:
            aws:
                $ref: '#/definitions/AWSConfig'
            file:
                type: string
            oci:
                $ref: '#/definitions/OciConfig'
            type:
                type: string
        type: object
    TLSConfig:
        properties:
            certFile:
                type: string
            enabled:
                type: boolean
            keyFile:
                type: string
        type: object
    VersionResponse:
        properties:
            buildDate:
                type: string
            buildType:
                type: string
            buildVersion:
                type: string
        type: object
    WebSocketConf:
        properties:
            pingPeriodSec:
                format: int64
                type: integer
            pongWaitSec:
                format: int64
                type: integer
            qredoWebsocket:
                type: string
            readBufferSize:
                format: int64
                type: integer
            reconnectIntervalSec:
                format: int64
                type: integer
            reconnectTimeoutSec:
                format: int64
                type: integer
            writeBufferSize:
                format: int64
                type: integer
            writeWaitSec:
                format: int64
                type: integer
        type: object
    WebsocketStatus:
        properties:
            connectedClients:
                format: uint32
                type: integer
            localFeedURL:
                type: string
            readyState:
                type: string
            remoteFeedURL:
                type: string
        type: object
host: localhost:8007
info:
    contact:
        email: support@qredo.com
        name: Qredo API Services
        url: https://www.qredo.com
    description: |-
        The Qredo Signing Agent service interacts with [Partner API](https://developers.qredo.com/partner-api/api/swagger/) to register a Signing Agent to automate approvals according to your custody policy. <br/>
        Authentication and encryption are required; set up your [API key and secret in the Qredo Web App](https://developers.qredo.com/signing-agent/v2-signing-agent/get-started/). <br/>
    license:
        name: APACHE 2.0
        url: https://www.apache.org/licenses/LICENSE-2.0
    title: Qredo Signing Agent V2
    version: 0.1.0
paths:
    /client:
        get:
            operationId: GetClient
            responses:
                "200":
                    description: GetClientResponse
                    schema:
                        $ref: '#/definitions/GetClientResponse'
            summary: Returns `agentID` if it's configured
            tags:
                - client
    /client/action/{action_id}:
        delete:
            operationId: actionReject
            parameters:
                - description: the ID of the transaction that is received from the feed
                  in: path
                  name: action_id
                  required: true
                  type: string
            responses:
                "200":
                    description: GenericResponse
                    schema:
                        $ref: '#/definitions/GenericResponse'
            summary: Reject a transaction
            tags:
                - action
        put:
            operationId: actionApprove
            parameters:
                - description: the ID of the transaction that is received from the feed
                  in: path
                  name: action_id
                  required: true
                  type: string
            responses:
                "200":
                    description: GenericResponse
                    schema:
                        $ref: '#/definitions/GenericResponse'
            summary: Approve a transaction
            tags:
                - action
    /client/feed:
        get:
            operationId: ClientFeed
            produces:
                - application/json
            responses:
                "200":
                    description: ClientFeedResponse
                    schema:
                        $ref: '#/definitions/ClientFeedResponse'
            schemes:
                - ws
                - wss
            summary: Get approval requests Feed (via websocket) from Qredo Backend
            tags:
                - client
    /client/register:
        post:
            operationId: RegisterAgent
            parameters:
                - in: body
                  name: Body
                  schema:
                    $ref: '#/definitions/ClientRegisterRequest'
            responses:
                "200":
                    description: ClientFullRegisterResponse
                    schema:
                        $ref: '#/definitions/ClientFullRegisterResponse'
            summary: Register a new agent
            tags:
                - client
    /healthcheck/config:
        get:
            operationId: HealthcheckConfig
            responses:
                "200":
                    description: ConfigResponse
                    schema:
                        $ref: '#/definitions/ConfigResponse'
            summary: Check application configuration
            tags:
                - healthcheck
    /healthcheck/status:
        get:
            operationId: HealthcheckStatus
            responses:
                "200":
                    description: HealthCheckStatusResponse
                    schema:
                        $ref: '#/definitions/HealthCheckStatusResponse'
            summary: Check application status
            tags:
                - healthcheck
    /healthcheck/version:
        get:
            operationId: HealthcheckVersion
            responses:
                "200":
                    description: VersionResponse
                    schema:
                        $ref: '#/definitions/VersionResponse'
            summary: Check application version
            tags:
                - healthcheck
schemes:
    - http
    - https
swagger: "2.0"
