stages:
  - unit-test
  - docker

Unit test:
  stage: unit-test
  image: golang:1.18.1
  tags:
    - amd64-eks
    - dev
  script:
    - echo "Running Unit tests from /scripts/test_coverage.sh"
    - sh scripts/test_coverage

variables:
  KANIKO_VERSION: "debug"

Build docker images:
  stage: docker
  when: manual
  image:
    name: gcr.io/kaniko-project/executor:$KANIKO_VERSION
    entrypoint: [""]
  tags:
    - amd64-eks
    - dev
  script:
    - /kaniko/executor
      --context=$CI_PROJECT_DIR
      --build-arg BUILD_TYPE="dev"
      --build-arg BUILD_DATE="$(date -u)"
      --dockerfile=dockerfiles/Dockerfile
      --no-push
      --destination=signing-agent
      --tarPath=signing-agent-$(date +%F).tar
  artifacts:
    expire_in: 1 hour
    paths:
      - signing-agent-*.tar
