stages:
  - unit-test

Unit test:
  stage: unit-test
  image: 965240221932.dkr.ecr.eu-west-1.amazonaws.com/automated-approver:dev
  tags:
    - "amd64-eks"
    - "dev"
  script:
    - ./scripts/test_coverage