stages:
  - unit-test

Unit test:
  stage: unit-test
  image: bitnami/gitlab-runner
  tags:
    - "amd64-eks"
    - "dev"
  script:
    - ./build.sh docker_unittest
    - docker run automated-approver-unittest:dev /bin/sh ./scripts/test_coverage