stages:
  - unit-test

Unit test:
  stage: unit-test
  image: golang:1.18.1
  tags:
    - amd64-eks
    - dev
  script:
    - echo "Running Unit tests from /scripts/test_coverage.sh"
    - sh scripts/test_coverage
