base:
  qredo_api_domain: play-api.qredo.network
  qredo_api_base_path: /api/v1/p
  store_file: /volume/ccstore.db
  auto_approve: false
  http_scheme: https
http:
  addr: 0.0.0.0:8007
  cors_allow_origins:
  - '*'
  proxy_forwarded_header: ""
  log_all_requests: true
logging:
  format: text
  level: debug
pin: 0