base:
  qredo_api_domain: play-api.qredo.network
  qredo_api_base_path: /api/v1/p
  auto_approve: false
  http_scheme: https
  store_type: file # oci/aws/az/file
  store_file: /volume/ccstore.db
  store_oci:
    compartment: ocid1.tenancy.oc1...
    vault: ocid1.vault.oc1...
    secret_encryption_key: ocid1.key.oc1...
    config_secret: automated_approver_config
  store_aws: ""
  # ...
  store_az: ""
  # ...
  pin: 0
http:
  addr: 127.0.0.1:8007
  cors_allow_origins:
    - '*'
  proxy_forwarded_header: ""
  log_all_requests: false
logging:
  format: text
  level: debug
redis:
  host: redis
  port: 6379
  password: ""
  db: 0
load_balancing:
  enable: true
  on_lock_error_timeout_ms: 300
  action_id_expiration_sec: 6
