base:
  qredo_api_domain: play-api.qredo.network
  qredo_api_base_path: /api/v1/p
  auto_approve: false
  http_scheme: https
  ws_scheme: wss
  pin: 0
http:
  addr: 0.0.0.0:8007
  cors_allow_origins:
    - '*'
  log_all_requests: false
logging:
  format: text
  level: debug
load_balancing:
  enable: false
  on_lock_error_timeout_ms: 300
  action_id_expiration_sec: 6
  redis:
    host: redis
    port: 6379
    password: ""
    db: 0
store: 
  type: file # oci/aws/az/file
  file: /volume/ccstore.db
  oci:
    compartment: ocid1.tenancy.oc1...
    vault: ocid1.vault.oc1...
    secret_encryption_key: ocid1.key.oc1...
    config_secret: automated_approver_config
  aws:
    region: aws-region-...
    config_secret: secrets_manager_secret...
  az: ""
  # ...