definitions:
  ClientRegisterFinishRequest:
    properties:
      accountCode:
        type: string
      clientID:
        type: string
      clientSecret:
        type: string
      id:
        type: string
      idDoc:
        type: string
    type: object
  ClientRegisterRequest:
    properties:
      apikey:
        type: string
      base64privatekey:
        type: string
      name:
        type: string
    type: object
  SignRequest:
    properties:
      message_hash_hex:
        type: string
    type: object
  VerifyRequest:
    properties:
      message_hash_hex:
        type: string
      signature_hex:
        type: string
      signer_id:
        type: string
    type: object
  clientRegisterFinishResponse:
    properties:
      feed_url:
        type: string
    type: object
  clientRegisterResponse:
    properties:
      bls_public_key:
        type: string
      ec_public_key:
        type: string
      ref_id:
        type: string
    type: object
  signResponse:
    properties:
      signature_hex:
        type: string
      signer_id:
        type: string
    type: object
paths:
  /client:
    get:
      description: Return AgentID if it's configured
      operationId: ClientsList
      responses:
        "200":
          $ref: '#/responses/string'
      tags:
      - clientsList
  /client/{client_id}/sign:
    post:
      description: Sign a payload
      operationId: payloadSign
      parameters:
      - in: body
        name: Body
        schema:
          $ref: '#/definitions/SignRequest'
      responses:
        "200":
          description: signResponse
          schema:
            $ref: '#/definitions/signResponse'
      tags:
      - payloads
  /client/action/{action_id}:
    delete:
      description: Reject action
      operationId: actionReject
      tags:
      - actions
    put:
      description: Approve action
      operationId: actionApprove
      tags:
      - actions
  /client/feed:
    post:
      description: Get approval requests Feed (via websocket) from Qredo Backend
      operationId: ClientFeed
      tags:
      - clientFeed
  /client/register:
    post:
      description: Client registration process (3 steps in one)
      operationId: ClientFullRegister
      responses:
        "200":
          $ref: '#/responses/ClientRegisterFinishResponse'
      tags:
      - clientFullRegister
  /verify:
    post:
      description: Verify a signature
      operationId: signatureVerify
      parameters:
      - in: body
        name: Body
        schema:
          $ref: '#/definitions/VerifyRequest'
      tags:
      - payloads
swagger: "2.0"
