version: '3.5'
services:
  aa:
    image: automated-approver:dev
    ports:
      - "8007"
    restart: "always"
    networks:
      - "aa.network"
    deploy:
      replicas: 3
    volumes:
      - ../../config.yaml:/volume/config.yaml
      - ../../ccstore.db:/volume/ccstore.db
    depends_on:
      - redis
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9090:9090"
    networks:
      - "aa.network"
    depends_on:
      - aa
  redis:
    image: redis:alpine
    container_name: "redis-db"
    ports:
      - '6379:6379'
    networks:
      - "aa.network"
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
networks:
  aa.network:
volumes:
  redis-data:
